CREATE TABLE PHIEUXUAT(
	SoPX VARCHAR(10) PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE VATTU(
	MaVTU VARCHAR(10) PRIMARY KEY,
    TenVTU VARCHAR(20)
);

CREATE TABLE PHIEUNHAP(
	SoPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE DONDH(
	SoDH VARCHAR(10) PRIMARY KEY,
    NgayDH DATE,
    MaNCC VARCHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

CREATE TABLE NHACC(
	MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC VARCHAR(20),
    DiaChi VARCHAR(50),
    SDT VARCHAR(15) UNIQUE
);

CREATE TABLE CHITIETPHIEUXUAT(
	SoPX VARCHAR(10),
    MaVTU VARCHAR(10),
    DGXuat DECIMAL(10, 2),
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CHITIETPHIEUNHAP(
	MaVTU VARCHAR(10),
    SoPN VARCHAR(10),
    DGNhap DECIMAL(10, 2),
    SLNhap INT,
    PRIMARY KEY (MaVTU, SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN)
);

CREATE TABLE CHITIETDONDATHANG(
	MaVTU VARCHAR(10),
    SoDH VARCHAR(10),
    PRIMARY KEY (MaVTU, SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH)
);