CREATE TABLE CUSTOMER(
	cID INT PRIMARY KEY,
    cNAME VARCHAR(25),
    cAGE TINYINT
);

CREATE TABLE ORDERBYCUSTOMER(
	oID INT PRIMARY KEY,
    oDATE DATETIME,
    oTOTALPRICE INT,
    cID INT,
    FOREIGN KEY (cID) REFERENCES CUSTOMER(cID)
);

CREATE TABLE PRODUCT(
	pID INT PRIMARY KEY,
    pNAME VARCHAR(25),
    pPRICE INT
);

CREATE TABLE ORDERDETAIL(
	oID INT,
    pID INT,
	odQTY INT,
    PRIMARY KEY (oID, pID),
    FOREIGN KEY (oID) REFERENCES ORDERBYCUSTOMER(oID),
    FOREIGN KEY (pID) REFERENCES PRODUCT(pID)
);