INSERT INTO CUSTOMER
VALUES 
	(1, 'Minh Quan', 10),
    (2, 'Ngoc Oanh', 20),
    (3, 'Hong Ha', 50);
    
INSERT INTO ORDERBYCUSTOMER (oID, cID, oDATE)
VALUES 
	(1, 1, '2006-03-21'),
    (2, 2, '2006-03-23'),
    (3, 1, '2006-03-16');
    
INSERT INTO PRODUCT
VALUES 
	(1, 'May Giat', 3),
    (2, 'Tu Lanh', 5),
    (3, 'Dieu Hoa', 7),
    (4, 'Quat', 1),
    (5, 'Bep Dien', 2);
    
INSERT INTO ORDERDETAIL
VALUES 
	(1, 1, 3),
    (1, 3, 7),
    (1, 4, 2),
    (2, 1, 1),
    (3, 1, 8),
    (2, 5, 4),
    (2, 3, 3);
    
SELECT oID, oDATE, oTOTALPRICE FROM ORDERBYCUSTOMER;

SELECT C.cNAME, P.pNAME FROM PRODUCT P
JOIN ORDERDETAIL OD ON P.pID = OD.pID
JOIN ORDERBYCUSTOMER OBC ON OD.oID = OBC.oID
JOIN CUSTOMER C ON OBC.cID = C.cID;

SELECT C.cNAME, P.pNAME FROM CUSTOMER C
LEFT JOIN ORDERBYCUSTOMER OBC ON OBC.cID = C.cID
LEFT JOIN ORDERDETAIL OD ON OD.oID = OBC.oID
LEFT JOIN PRODUCT P ON P.pID = OD.pID
WHERE P.pNAME IS NULL;

SELECT OBC.oID, OBC.oDATE, OD.odQTY * P.pPRICE AS TOTALPRICE FROM ORDERBYCUSTOMER OBC
JOIN ORDERDETAIL OD ON OBC.oID = OD.oID
JOIN PRODUCT P ON OD.pID = P.pID;